
using System.Collections.Generic;

namespace HFM.Client.DataTypes
{
   /// <summary>
   /// Provides the base functionality for creating Folding@Home typed client messages.
   /// </summary>
   public abstract class TypedMessage : TypedMessageBase
   {
      public abstract void Fill(JsonMessage message);
   }

   /// <summary>
   /// Provides the base functionality for creating Folding@Home typed client messages.
   /// </summary>
   public abstract class TypedMessageBase : Message
   {
      /// <summary>
      /// Initializes a new instance of the <see cref="TypedMessageBase"/> class.
      /// </summary>
      protected TypedMessageBase()
      {
         _errors = new List<TypedMessagePropertyError>();
      }

      private readonly List<TypedMessagePropertyError> _errors;
      /// <summary>
      /// Gets a collection of property errors.
      /// </summary>
      public ICollection<TypedMessagePropertyError> Errors
      {
         get { return _errors.AsReadOnly(); }
      }

      /// <summary>
      /// Adds a message property error.
      /// </summary>
      public void AddError(TypedMessagePropertyError error)
      {
         _errors.Add(error);
      }
   }

   /// <summary>
   /// Folding@Home message property conversion error. This class cannot be inherited.
   /// </summary>
   public sealed class TypedMessagePropertyError
   {
      /// <summary>
      /// Gets the class property name the conversion failed to populate.
      /// </summary>
      public string PropertyName { get; }

      /// <summary>
      /// Gets the error message generated by the conversion failure.
      /// </summary>
      public string Message { get; }

      internal TypedMessagePropertyError(string propertyName, string message)
      {
         PropertyName = propertyName;
         Message = message;
      }
   }
}