//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("harlam357")]
[assembly: System.Reflection.AssemblyProduct("HFM.NET")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Ryan Harlamert 2009-2019.")]
[assembly: System.Reflection.AssemblyVersion("0.9.12.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.12.0")]


